import { defineConfig, devices } from "@playwright/test";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = path.dirname(fileURLToPath(import.meta.url));
const PORT = 4174;
const BASE_URL = `http://localhost:${PORT}`;
const FIXTURE_ROOT = path.join(REPO_ROOT, ".generated", "autoresearch-e2e", "root");
const PRIVATE_ROOT = path.join(REPO_ROOT, "tests", "fixtures", "autoresearch", "fake-private");
const FAKE_CODEX = path.join(REPO_ROOT, "tests", "fixtures", "autoresearch", "fake-codex.mjs");
const FIXED_TIME = "2026-07-28T08:00:00.000Z";

function cleanEnvironment() {
  return Object.fromEntries(
    Object.entries(process.env).filter((entry): entry is [string, string] => typeof entry[1] === "string"),
  );
}

function writeAutoresearchFixture() {
  const problemDir = path.join(FIXTURE_ROOT, "problems", "Prob-001");
  rmSync(FIXTURE_ROOT, { recursive: true, force: true });
  mkdirSync(problemDir, { recursive: true });
  writeFileSync(path.join(problemDir, "problem.json"), `${JSON.stringify({
    schemaVersion: 1,
    id: "Prob-001",
    title: "Fixture autoresearch preparation problem",
    summary: "A qualifying local problem for the fake autoresearch preparation loop.",
    status: "qualifying",
    gate: { type: "fixture", readiness: "specified" },
    provenance: { sourceCount: 0 },
    lastActivity: { summary: "Created fixture problem", at: FIXED_TIME },
    createdAt: FIXED_TIME,
    updatedAt: FIXED_TIME,
  }, null, 2)}\n`);
  writeFileSync(path.join(problemDir, "problem.md"), [
    "# Background and Gap",
    "",
    "The fixture needs a benchmark scaffold before any attempt batch may run.",
    "",
    "# Research Objective",
    "",
    "Prepare a tiny deterministic score benchmark.",
    "",
    "# Publication Threshold",
    "",
    "A candidate passes when the fixture score reaches 7.",
    "",
    "# Executable Gate",
    "",
    "The fake infrastructure must pass public, containment, and private evaluator checks.",
    "",
    "# Novelty Evidence",
    "",
    "This is a local-only E2E fixture, not trusted knowledge.",
    "",
    "# Provenance",
    "",
    "Generated by the autoresearch Playwright fixture.",
    "",
    "# Fresh Evaluation Plan",
    "",
    "Ask for the metric once, then publish INF-001 after preflight passes.",
    "",
  ].join("\n"));
}

writeAutoresearchFixture();

export default defineConfig({
  testDir: "tests/e2e",
  testMatch: /local-autoresearch-preparation\.spec\.ts/,
  timeout: 90_000,
  fullyParallel: false,
  forbidOnly: Boolean(process.env.CI),
  retries: 0,
  workers: 1,
  reporter: [["list"]],
  use: {
    baseURL: BASE_URL,
    trace: "on-first-retry",
  },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
  webServer: {
    command: "npm run dev",
    cwd: REPO_ROOT,
    env: {
      ...cleanEnvironment(),
      AUTORESEARCH_WORKSPACE_ROOT: FIXTURE_ROOT,
      AUTORESEARCH_PRIVATE_ROOT: PRIVATE_ROOT,
      AUTORESEARCH_CODEX_PATH: FAKE_CODEX,
      AUTORESEARCH_DEV_HOST: "localhost",
      AUTORESEARCH_DEV_PORT: String(PORT),
    },
    url: BASE_URL,
    reuseExistingServer: false,
    timeout: 300_000,
    gracefulShutdown: { signal: "SIGTERM", timeout: 10_000 },
    stdout: "pipe",
    stderr: "pipe",
  },
});
